TELESTION-460 Dashboard layout editor
wuespace/telestion pull request #417
Opened 2024-01-14 22:40 UTC by pklaschka

A layout editor for dashboards to make them configurable by users.

Interaction can be performed using both the mouse and the keyboard.

Changes are handled completely independently from the UI, allowing for both an easier way to ensure invalid states cannot occur as well as testability. During the user interaction, no actual state changes are performed. Once the interaction finishes, the changes get interpreted to the closest possible state change and "committed" to the state, where (in compliance with any business logic) the changes are applied and, thus, updates in the UI. This also allows us to implement any interactions without absolute positioning and resize observers. Instead, the native CSS grid can be used.

Due to the relative complexity and clear boundaries of this subsystem, a separate folder structure which also includes a `README.md` was created.

2024-01-14 22:41 UTC, pklaschka commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/wuespace/telestion/417?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #411** <a href="https://app.graphite.dev/github/pr/wuespace/telestion/411?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #412** <a href="https://app.graphite.dev/github/pr/wuespace/telestion/412?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #417** <a href="https://app.graphite.dev/github/pr/wuespace/telestion/417?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/wuespace/telestion/417?utm_source=stack-comment).

2024-01-17 21:38 UTC, pklaschka commented on frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/util.tsx
Remove this; it's nice to be snappy with the keyboard and drag and drop doesn't need it anyways.

2024-01-19 10:10 UTC, pklaschka commented on frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/README.md
> +- widget selected
Update this based on the `model/layout-editor-props.ts`

2024-01-19 10:12 UTC, pklaschka commented on frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/layout-editor.tsx
> +	} satisfies LayoutEditorState);
Replace with outer state through `LayoutEditorProps`

2024-01-21 16:40 UTC, pklaschka commented on frontend-react/src/lib/application/routes/page-wrapper/page-wrapper.module.css
> +}
Add comments explaining why this is done

2024-01-21 16:41 UTC, pklaschka commented on frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/model/layout-editor-model.ts
Add doc comments

2024-01-21 16:42 UTC, pklaschka commented on frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/hooks/use-layout-editor-keyboard-shortcuts.tsx
> +) {
Add a doc comment

2024-01-26 18:09 UTC, fussel178 requested changes
Some little things. The rest looks good to me. :smile:

2024-01-26 18:15 UTC, fussel178 approved these changes

2024-01-26 18:15 UTC, merged

2024-01-26 18:15 UTC, pklaschka commented
### Merge activity

* **Jan 26, 7:15 PM**: @pklaschka merged this pull request with [Graphite](https://app.graphite.dev/github/pr/wuespace/telestion/417).